name: pipeline
on: [push, pull_request]

jobs:
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: clippy, rustfmt
      - run: cargo fmt --version
      - uses: actions-rs/cargo@v1
        name: Format
        with:
          command: fmt
          args: --all -- --check
      - run: cargo clippy --version
      - uses: actions-rs/cargo@v1
        name: Clippy
        with:
          command: clippy
          args: -- -D warnings

  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        name: Test (and build debug)
        with:
          command: test
      - uses: actions-rs/cargo@v1
        name: Build release
        with:
          command: build
          args: --release
      - name: Publish to crates.io
        if: ${{ startsWith(github.ref, 'refs/tags') }}
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --token ${{ secrets.CRATES_IO_TOKEN }}
